# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c6d9dce47939408ad470bd75701e6dcc2f812a66767ed486d88173ae6f980b492e8a083021f4f428407dc4c212aec01e1b853cc2e36df2780ad8e627e362f00

test:
  secret_key_base: c162e2e7e9ef808a6f54c61063b7f79700fb63a6ca86e36ff466272053a792edca263eaa2a4d1fda8fa492d4f95b235ad1a8fc39df59f49dcc9d83b982f9278a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
